/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PI17;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Fidel
 */
public class Escuelas extends javax.swing.JFrame {

    /**
     * Creates new form Escuelas
     */
    
    Principal p;
    Connection con;
    DBConection db;
    
    
    public Escuelas() {
        initComponents();
        myInitComponents();
    }
    
    public void Principal(Principal p){
        this.p=p;
    }
    
    private void mostrarEscuelas(){
        try {
            
            db.comando = (Statement) db.conexion.createStatement();
            String query="SELECT * FROM Escuelas ORDER BY 2 ASC";
            db.registro = db.comando.executeQuery(query); 
            DefaultListModel modelo=new DefaultListModel();
            while (db.registro.next()) {
                modelo.addElement(db.registro.getString(2));
            }
            lstEscuelas.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Escuelas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEscuelas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lstEscuelas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEscuelasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEscuelas);

        jButton1.setText("Cambiar nombre");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar escuela");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar escuela");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents(){
        db=new DBConection();
        con=db.MySQLConnect();
        mostrarEscuelas();
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        p.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void lstEscuelasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEscuelasValueChanged
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_lstEscuelasValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String escuela="";
        escuela=JOptionPane.showInputDialog(null, "Nombre de la escuela", "Escuela", 1);
        System.out.println(escuela);
        if (escuela != null) {
            try {
                db.comando = (Statement) db.conexion.createStatement();
                String query="UPDATE Escuelas SET Nombre='"+escuela.toUpperCase()+"' WHERE Nombre='"+lstEscuelas.getSelectedValue()+"'";
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "La escuela fue actualizada");
                mostrarEscuelas();
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "La escuela no pudo ser actualizada");
                 
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int dialog=JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar esta escuela?");
        if (dialog==JOptionPane.YES_OPTION) {
            try {
                db.comando = (Statement) db.conexion.createStatement();
                String query="DELETE FROM Escuelas WHERE Nombre='"+lstEscuelas.getSelectedValue()+"'";
                System.out.println(query);
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Se ha borrado la escuela seleccionada");
                mostrarEscuelas();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se ha podido borrar la escuela seleccionada");
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nuevo="";
        nuevo=JOptionPane.showInputDialog(null, "Nombre de la nueva escuela", "Agregar escuela", 1);
        if (nuevo!=null) {
            try {
                db.comando = (Statement) db.conexion.createStatement();
                String query="INSERT INTO Escuelas (Id_Escuela, Nombre) VALUES (NULL, '"+nuevo.toUpperCase()+"')";
                System.out.println(query);
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Se ha agregado la escuela ");
                mostrarEscuelas();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se ha podido agregar la escuela ");
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escuelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstEscuelas;
    // End of variables declaration//GEN-END:variables
}
